ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "RequiresApproval" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "ProposalId" VARCHAR(20);
ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "SimulatedImpact" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "ApprovalStatus" VARCHAR(20) NOT NULL DEFAULT '';
